# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += widgets gui core
TEMPLATE = app
TARGET = VLCplayer
DESTDIR = ./bin

include($$PWD/sdk/vlc.pri)


HEADERS += vlcplayer.h
SOURCES += ./main.cpp \
    ./vlcplayer.cpp

FORMS += $$PWD/vlcplayer.ui

